services:
  auth_service:
    build: ./auth_service
    ports:
      - "3005:3005"
    networks:
      - ashchat_network

  email_service:
    build: ./email_service
    environment:
      - SMTP_EMAIL=${SMTP_EMAIL}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
    networks:
      - ashchat_network
    
  translate_service:
    build: ./translate_service
    networks:
      - ashchat_network

  chat_service:
    build: ./chat_service
    ports:
      - "4000:4000"
    networks:
      - ashchat_network

  static_service:
    build: ./static_service
    ports:
      - "3006:3006"
    volumes:
      - ashchat_static_volume:/app/uploads
    networks:
      - ashchat_network

networks:
  ashchat_network:
    external: true

volumes:
  ashchat_static_volume: