### eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0eXBlIjoiTUFJTiIsImlhdCI6MTczMDcyMTYwNywiZXhwIjoxNzMxMzI2NDA3LCJzdWIiOiI2NzI4YjczODIwOGU3YjFlOTgzYzFhYjIifQ.Q5OfBo_-d6M_doh-MrIKK0BDB7z-spGHvrOGtZQNVys

# eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0eXBlIjoiTUFJTiIsImlhdCI6MTczMDcyMTcwNCwiZXhwIjoxNzMxMzI2NTA0LCJzdWIiOiI2NzI4Yjc5ZjIwOGU3YjFlOTgzYzFhYjcifQ.rUuHPccrAbO6xXysb2hb417vJJpz83UqJZTJcT5DW8E

### Register a new user
POST http://localhost:3005/api/user/register 
Content-Type: application/json

{
    "email": "ashdadelikia@gmail.com",
    "password": "password123",
    "nickname": "Ash_2",
    "preferredLanguage": "pt"
}

### Login a user
POST http://localhost:3005/api/user/login
Content-Type: application/json

{
    "email": "ashdadelikia@gmail.com",
    "password": "password123"
}

### Confirm email code
POST http://localhost:3005/api/user/confirm-email
Content-Type: application/json

{
    "email": "ashdadelikia@gmail.com",
    "emailCode": "814704"
}

### Change user password
POST http://localhost:3005/api/user/change-password
Content-Type: application/json

{
    "email": "user@example.com",
    "oldPassword": "password123",
    "newPassword": "newpassword123"
}

### Confirm change user password
POST http://localhost:3005/api/user/confirm-change-password
Content-Type: application/json
Authorization: Bearer <temporary_jwt_token>

{
    "email": "user@example.com",
    "code": "123456"
}