_format_version: "3.0"
_transform: true

services:
  - name: auth_service
    id: 97a6e553-99d9-4a68-94f3-c3b5b0d70281
    tags:
      - auth
    protocol: http
    host: ashchatAuthService
    port: 3005
    path: /auth
    retries: 5
    connect_timeout: 60000
    read_timeout: 60000
    write_timeout: 60000
    tls_verify_value: false
    tls_verify_enabled: false

  - name: chat-service
    id: 55761adf-6ba0-45c1-ab84-e5e6f84e8e74
    tags:
      - chat-service
    protocol: http
    host: ashchatChatService
    port: 4000
    retries: 5
    connect_timeout: 60000
    read_timeout: 60000
    write_timeout: 60000
    tls_verify_value: false
    tls_verify_enabled: false

routes:
  - name: auth-routing
    service:
      id: 97a6e553-99d9-4a68-94f3-c3b5b0d70281
    paths:
      - /auth
    protocols:
      - http
      - https
    methods:
      - GET
      - PUT
      - POST
      - PATCH
      - DELETE
      - OPTIONS
    regex_priority: 0
    path_handling: v0
    strip_path: true
    preserve_host: false
    request_buffering: true
    response_buffering: true
    tags:
      - auth

  - name: chat-routing
    service:
      id: 55761adf-6ba0-45c1-ab84-e5e6f84e8e74
    paths:
      - /chat
    protocols:
      - http
      - https
    methods:
      - GET
      - PUT
      - POST
      - PATCH
      - DELETE
      - OPTIONS
    regex_priority: 0
    path_handling: v0
    strip_path: true
    preserve_host: false
    request_buffering: true
    response_buffering: true
    tags:
      - chat-service

plugins:
  - name: cors
    id: fc20e8f1-749c-4824-bd07-292ce8fdcb0f
    enabled: true
    tags:
      - security-client
    protocols:
      - http
      - https
      - grpc
      - grpcs
    config:
      origins:
        - http://localhost:5173
        - http://localhost:8081
      methods:
        - GET
        - HEAD
        - PUT
        - PATCH
        - POST
        - DELETE
        - OPTIONS
      # headers:
      #   - Content-Type
      #   - Authorization
      #   - X-Requested-With
      # exposed_headers:
      #   - device_token
      credentials: false
      preflight_continue: false
      max_age: 3600
