services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_container_dev
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - ashchat_network
    volumes:
      - mongo-data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_container_dev
    ports:
      - "5672:5672"   # default port
      - "15672:15672" # web management interface
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: randompassword
    networks:
      - ashchat_network

  redis:
    image: redis:latest
    container_name: redis_container_dev
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=yourpassword 
    command: ["redis-server", "--requirepass", "yourpassword"]
    networks:
      - ashchat_network
    volumes:
      - redis_data:/data

volumes:
  mongo-data:
    driver: local
  redis_data:
    driver: local

networks:
  ashchat_network:
    external: true