export const languages = [
    { label: 'English', value: 'en', flag: 'US' },
    { label: 'Español', value: 'es', flag: 'ES' },
    { label: 'Français', value: 'fr', flag: 'FR' },
    { label: 'Portuguese', value: 'pt', flag: 'PT' },
    { label: 'Deutsch', value: 'de', flag: 'DE' },
    { label: 'Italian', value: 'it', flag: 'IT' },
    { label: 'Dutch', value: 'nl', flag: 'NL' },
    { label: 'Russian', value: 'ru', flag: 'RU' },
    { label: 'Japanese', value: 'ja', flag: 'JP' },
    { label: 'Chinese', value: 'zh', flag: 'CN' },
    { label: 'Korean', value: 'ko', flag: 'KR' },
    { label: 'Arabic', value: 'ar', flag: 'SA' },
    { label: 'Turkish', value: 'tr', flag: 'TR' },
    { label: 'Hindi', value: 'hi', flag: 'IN' },
    { label: 'Bengali', value: 'bn', flag: 'BD' },
    { label: 'Urdu', value: 'ur', flag: 'PK' },
    { label: 'Vietnamese', value: 'vi', flag: 'VN' },
  ];